// Title screen (tools/make_title.py), 16 colours on PAL0.
IMAGE title_image "gfx/title.png" NONE

// Companion avatars for the party panel (tools/make_avatar.py), all on PAL1 with one shared
// palette (loaded from avatar_wir_sprite in main.c).
SPRITE avatar_wir_sprite "gfx/avatar_wir.png" 3 3
SPRITE avatar_laezel_sprite "gfx/avatar_laezel.png" 3 3
SPRITE avatar_shadowheart_sprite "gfx/avatar_shadowheart.png" 3 3

// Figures shown in front of the view in dialogue scenes and combat (tools/make_figures.py), on
// PAL2, each with its own palette (src/figures.c loads it when the figure is shown). The imp's
// three frames are its wing beat, advanced every 6 frames. Busts are the close-ups while a
// companion speaks.
SPRITE fig_imp_sprite "gfx/fig_imp.png" 4 6 NONE 6
SPRITE fig_laezel_sprite "gfx/fig_laezel.png" 6 12 NONE 0
SPRITE fig_shadowheart_sprite "gfx/fig_shadowheart.png" 6 12 NONE 0
SPRITE fig_laezel_bust_sprite "gfx/fig_laezel_bust.png" 10 12 NONE 0
SPRITE fig_shadowheart_bust_sprite "gfx/fig_shadowheart_bust.png" 10 12 NONE 0
SPRITE fig_arrow_sprite "gfx/fig_arrow.png" 1 1 NONE 0
SPRITE fig_hound_sprite "gfx/fig_hound.png" 6 5 NONE 0
SPRITE fig_cambion_sprite "gfx/fig_cambion.png" 6 12 NONE 0
SPRITE fig_zhalk_sprite "gfx/fig_zhalk.png" 8 14 NONE 0
SPRITE fig_mindflayer_bust_sprite "gfx/fig_mindflayer_bust.png" 10 12 NONE 0

// SGDK's default font with German umlauts in 7 unused ASCII slots (tools/make_font.py, used via
// src/text.c). NONE/NONE: VDP_loadFont needs all 96 glyphs in order.
TILESET font_de "gfx/font_de.png" NONE NONE

// First-person view data, generated by tools/make_view.py (together with src/view_gen.h):
// every wall column the view can show, pre-textured and pre-shaded, one block per texture...
BIN viewColumns "view/columns.bin" 2 2 0 NONE
// ...the static floor/ceiling backdrop plus its mirror image, in VDP tile layout...
BIN viewBackdrops "view/backdrops.bin" 4 4 0 NONE
// ...and the finished full view of a wall right in front of the player, one per texture.
BIN viewAdjacent "view/adjacent.bin" 4 4 0 NONE
// ...and the free-standing objects (props), pre-scaled per distance, with transparency masks.
BIN viewProps "view/props.bin" 2 2 0 NONE

// Hero portraits (tools/make_portraits.py): three per starting class, an 80x96 bust for the
// creation screen and the 24x24 panel avatar scaled down from it. Each pair has its own palette,
// loaded into PAL3 (the text palette -- the font only uses colour 15, which stays white).
SPRITE portrait_fighter_1 "gfx/portrait_fighter_1.png" 10 12 NONE 0
SPRITE hero_fighter_1 "gfx/hero_fighter_1.png" 3 3 NONE 0
SPRITE portrait_fighter_2 "gfx/portrait_fighter_2.png" 10 12 NONE 0
SPRITE hero_fighter_2 "gfx/hero_fighter_2.png" 3 3 NONE 0
SPRITE portrait_fighter_3 "gfx/portrait_fighter_3.png" 10 12 NONE 0
SPRITE hero_fighter_3 "gfx/hero_fighter_3.png" 3 3 NONE 0
SPRITE portrait_rogue_1 "gfx/portrait_rogue_1.png" 10 12 NONE 0
SPRITE hero_rogue_1 "gfx/hero_rogue_1.png" 3 3 NONE 0
SPRITE portrait_rogue_2 "gfx/portrait_rogue_2.png" 10 12 NONE 0
SPRITE hero_rogue_2 "gfx/hero_rogue_2.png" 3 3 NONE 0
SPRITE portrait_rogue_3 "gfx/portrait_rogue_3.png" 10 12 NONE 0
SPRITE hero_rogue_3 "gfx/hero_rogue_3.png" 3 3 NONE 0
SPRITE portrait_mage_1 "gfx/portrait_mage_1.png" 10 12 NONE 0
SPRITE hero_mage_1 "gfx/hero_mage_1.png" 3 3 NONE 0
SPRITE portrait_mage_2 "gfx/portrait_mage_2.png" 10 12 NONE 0
SPRITE hero_mage_2 "gfx/hero_mage_2.png" 3 3 NONE 0
SPRITE portrait_mage_3 "gfx/portrait_mage_3.png" 10 12 NONE 0
SPRITE hero_mage_3 "gfx/hero_mage_3.png" 3 3 NONE 0
