// Generic hero avatar (see tools/make_avatar.py), used on the character creation screen and
// in the party panel. Carries its own palette (PAL1) via avatar_sprite.palette.
SPRITE avatar_sprite "gfx/avatar.png" 3 3

// SGDK's default font with German umlauts in 7 unused ASCII slots (tools/make_font.py, used via
// src/text.c). NONE/NONE: VDP_loadFont needs all 96 glyphs in order.
TILESET font_de "gfx/font_de.png" NONE NONE

// First-person view data, generated by tools/make_view.py (together with src/view_gen.h):
// every wall column the view can show, pre-textured and pre-shaded, one block per texture...
BIN viewColumns "view/columns.bin" 2 2 0 NONE
// ...the static floor/ceiling backdrop plus its mirror image, in VDP tile layout...
BIN viewBackdrops "view/backdrops.bin" 4 4 0 NONE
// ...and the finished full view of a wall right in front of the player, one per texture.
BIN viewAdjacent "view/adjacent.bin" 4 4 0 NONE
